name: GitHub Actions Demo
on:
  push:
    branches:
      - main
      - master
jobs:
  PoC-Repo-Search-Checks-As-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3


      - run: service_name=$(jq .name package.json)

      - name: "Perform the check"
        run: |
          # exclude *this* file (the one you're reading) since it's yml
          files=$(find . -name '*.yml' | grep -v '.github/workflows/')
          grep --silent 'yarn test-audit' ${files}
          result=$?

          if [ result ]; then
            check_passed="true"
          else
            check_passed="false"
          fi
          echo "Check passed: ${check_passed}"

          payload={"\"service\": ${service_name}, \"has_yarn_test_audit\": ${check_passed} }"
          curl -i -X POST -d "${payload}" https://opslevel-sergio.ngrok.io/integrations/custom_event/50054f4a-5bd7-4bbb-b6cb-280b621ec3c3
