name: GitHub Actions Demo
on:
  push:
    branches:
      - main
      - master
jobs:
  PoC-Repo-Search-Checks-As-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: "Perform the check"
        run: |
          # Search for a string in all yml files

          search_term="yarn test-audit"

          files=$(find . -name '*.yml')



          # Exclude *this* file (the one you're reading) since it will always match the search
          files=$(echo "${files}" | grep -v '.github/workflows/')
          # echo -e "Searching these files: ${files}\n"

          if grep --silent "${search_term}" ${files}; then
            check_passed="true"
          else
            check_passed="false"
          fi
          echo -e "\nCheck passed: ${check_passed}\n"

          service_name=$(jq .name package.json)
          echo -e "Service name: ${service_name}\n"

          payload={"\"service\": ${service_name}, \"has_yarn_test_audit\": ${check_passed} }"
          curl -s -X POST -d "${payload}" https://opslevel-sergio.ngrok.io/integrations/custom_event/50054f4a-5bd7-4bbb-b6cb-280b621ec3c3
